version: '3.4'

services:
  server:
    build:
      context: ./server
      target: dev
    env_file:
      - ./server/.env.local
    restart: unless-stopped
    ports:
      - 5001:5001

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - auth-db:/data/db

volumes:
  auth-db:
    driver: local
